/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAgentsRouteImport } from './routes/ai-agents'
import { Route as ClientApprovalsRouteImport } from './routes/client-approvals'
import { Route as ClientChangeRequestsRouteImport } from './routes/client-change-requests'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EmployeeHistoryRouteImport } from './routes/employee-history'
import { Route as ExportCenterRouteImport } from './routes/export-center'
import { Route as ImportCenterRouteImport } from './routes/import-center'
import { Route as ImportHistoryRouteImport } from './routes/import-history'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PermissionManagementRouteImport } from './routes/permission-management'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentsRoute = AiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientApprovalsRoute = ClientApprovalsRouteImport.update({
  id: '/client-approvals',
  path: '/client-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientChangeRequestsRoute = ClientChangeRequestsRouteImport.update({
  id: '/client-change-requests',
  path: '/client-change-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeHistoryRoute = EmployeeHistoryRouteImport.update({
  id: '/employee-history',
  path: '/employee-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportCenterRoute = ExportCenterRouteImport.update({
  id: '/export-center',
  path: '/export-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportCenterRoute = ImportCenterRouteImport.update({
  id: '/import-center',
  path: '/import-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportHistoryRoute = ImportHistoryRouteImport.update({
  id: '/import-history',
  path: '/import-history',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionManagementRoute = PermissionManagementRouteImport.update({
  id: '/permission-management',
  path: '/permission-management',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/client-approvals': typeof ClientApprovalsRoute
  '/client-change-requests': typeof ClientChangeRequestsRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/employee-history': typeof EmployeeHistoryRoute
  '/export-center': typeof ExportCenterRoute
  '/import-center': typeof ImportCenterRoute
  '/import-history': typeof ImportHistoryRoute
  '/knowledge': typeof KnowledgeRoute
  '/learning': typeof LearningRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/performance': typeof PerformanceRoute
  '/permission-management': typeof PermissionManagementRoute
  '/recruitment': typeof RecruitmentRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/client-approvals': typeof ClientApprovalsRoute
  '/client-change-requests': typeof ClientChangeRequestsRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/employee-history': typeof EmployeeHistoryRoute
  '/export-center': typeof ExportCenterRoute
  '/import-center': typeof ImportCenterRoute
  '/import-history': typeof ImportHistoryRoute
  '/knowledge': typeof KnowledgeRoute
  '/learning': typeof LearningRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/performance': typeof PerformanceRoute
  '/permission-management': typeof PermissionManagementRoute
  '/recruitment': typeof RecruitmentRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/client-approvals': typeof ClientApprovalsRoute
  '/client-change-requests': typeof ClientChangeRequestsRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/employee-history': typeof EmployeeHistoryRoute
  '/export-center': typeof ExportCenterRoute
  '/import-center': typeof ImportCenterRoute
  '/import-history': typeof ImportHistoryRoute
  '/knowledge': typeof KnowledgeRoute
  '/learning': typeof LearningRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/performance': typeof PerformanceRoute
  '/permission-management': typeof PermissionManagementRoute
  '/recruitment': typeof RecruitmentRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agents'
    | '/client-approvals'
    | '/client-change-requests'
    | '/clients'
    | '/documents'
    | '/employee-history'
    | '/export-center'
    | '/import-center'
    | '/import-history'
    | '/knowledge'
    | '/learning'
    | '/leave'
    | '/login'
    | '/performance'
    | '/permission-management'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/teams'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agents'
    | '/client-approvals'
    | '/client-change-requests'
    | '/clients'
    | '/documents'
    | '/employee-history'
    | '/export-center'
    | '/import-center'
    | '/import-history'
    | '/knowledge'
    | '/learning'
    | '/leave'
    | '/login'
    | '/performance'
    | '/permission-management'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/teams'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/ai-agents'
    | '/client-approvals'
    | '/client-change-requests'
    | '/clients'
    | '/documents'
    | '/employee-history'
    | '/export-center'
    | '/import-center'
    | '/import-history'
    | '/knowledge'
    | '/learning'
    | '/leave'
    | '/login'
    | '/performance'
    | '/permission-management'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/teams'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentsRoute: typeof AiAgentsRoute
  ClientApprovalsRoute: typeof ClientApprovalsRoute
  ClientChangeRequestsRoute: typeof ClientChangeRequestsRoute
  ClientsRoute: typeof ClientsRoute
  DocumentsRoute: typeof DocumentsRoute
  EmployeeHistoryRoute: typeof EmployeeHistoryRoute
  ExportCenterRoute: typeof ExportCenterRoute
  ImportCenterRoute: typeof ImportCenterRoute
  ImportHistoryRoute: typeof ImportHistoryRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LearningRoute: typeof LearningRoute
  LeaveRoute: typeof LeaveRoute
  LoginRoute: typeof LoginRoute
  PerformanceRoute: typeof PerformanceRoute
  PermissionManagementRoute: typeof PermissionManagementRoute
  RecruitmentRoute: typeof RecruitmentRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TeamsRoute: typeof TeamsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agents': {
      id: '/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-approvals': {
      id: '/client-approvals'
      path: '/client-approvals'
      fullPath: '/client-approvals'
      preLoaderRoute: typeof ClientApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-change-requests': {
      id: '/client-change-requests'
      path: '/client-change-requests'
      fullPath: '/client-change-requests'
      preLoaderRoute: typeof ClientChangeRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-history': {
      id: '/employee-history'
      path: '/employee-history'
      fullPath: '/employee-history'
      preLoaderRoute: typeof EmployeeHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-center': {
      id: '/export-center'
      path: '/export-center'
      fullPath: '/export-center'
      preLoaderRoute: typeof ExportCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-center': {
      id: '/import-center'
      path: '/import-center'
      fullPath: '/import-center'
      preLoaderRoute: typeof ImportCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-history': {
      id: '/import-history'
      path: '/import-history'
      fullPath: '/import-history'
      preLoaderRoute: typeof ImportHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permission-management': {
      id: '/permission-management'
      path: '/permission-management'
      fullPath: '/permission-management'
      preLoaderRoute: typeof PermissionManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentsRoute: AiAgentsRoute,
  ClientApprovalsRoute: ClientApprovalsRoute,
  ClientChangeRequestsRoute: ClientChangeRequestsRoute,
  ClientsRoute: ClientsRoute,
  DocumentsRoute: DocumentsRoute,
  EmployeeHistoryRoute: EmployeeHistoryRoute,
  ExportCenterRoute: ExportCenterRoute,
  ImportCenterRoute: ImportCenterRoute,
  ImportHistoryRoute: ImportHistoryRoute,
  KnowledgeRoute: KnowledgeRoute,
  LearningRoute: LearningRoute,
  LeaveRoute: LeaveRoute,
  LoginRoute: LoginRoute,
  PerformanceRoute: PerformanceRoute,
  PermissionManagementRoute: PermissionManagementRoute,
  RecruitmentRoute: RecruitmentRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TeamsRoute: TeamsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
